apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: nginx
  labels:
    app: nginx
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/data"
